default = (
    "admin",
    "auctions",
    "battling",
    "bot",
    "config",
    "data",
    "help",
    "market",
    "mongo",
    "pokemon",
    "quests",
    "redis",
    "shop",
    "spawning",
    "incenses",
    "sprites",
    "trading",
    # "event",  # Cog for simple events, remove when bigger event cogs are added.
)
